FROM albertoleal/wily
MAINTAINER Alberto Leal <albertonb@gmail.com>

RUN set -x \
  && go get github.com/onsi/ginkgo/ginkgo \
  && go get github.com/onsi/gomega

RUN set -x \
  && git clone https://github.com/hashicorp/consul $GOPATH/src/github.com/hashicorp/consul \
	&& cd $(GOPATH)/src/github.com/hashicorp/consul \
	&& CONSUL_DEV=true make \
	&& mv bin/consul $(GOPATH)/bin

WORKDIR $GOPATH/src/github.com/apihub/apihub/
