#!/bin/bash
set -e

# Create dir structure for database and keys
mkdir -p ./database
mkdir -p ./keys/web
mkdir -p ./keys/worker

# Generate keys
ssh-keygen -t rsa -f ./keys/web/tsa_host_key -N ''
ssh-keygen -t rsa -f ./keys/web/session_signing_key -N ''
ssh-keygen -t rsa -f ./keys/worker/worker_key -N ''
cp ./keys/worker/worker_key.pub ./keys/web/authorized_worker_keys
cp ./keys/web/tsa_host_key.pub ./keys/worker

