// This file was generated by counterfeiter
package apihubfakes

import (
	"sync"

	"code.cloudfoundry.org/lager"
	"github.com/apihub/apihub"
)

type FakeServiceSubscriber struct {
	SubscribeStub        func(logger lager.Logger, spec apihub.ServiceSpec) error
	subscribeMutex       sync.RWMutex
	subscribeArgsForCall []struct {
		logger lager.Logger
		spec   apihub.ServiceSpec
	}
	subscribeReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceSubscriber) Subscribe(logger lager.Logger, spec apihub.ServiceSpec) error {
	fake.subscribeMutex.Lock()
	fake.subscribeArgsForCall = append(fake.subscribeArgsForCall, struct {
		logger lager.Logger
		spec   apihub.ServiceSpec
	}{logger, spec})
	fake.recordInvocation("Subscribe", []interface{}{logger, spec})
	fake.subscribeMutex.Unlock()
	if fake.SubscribeStub != nil {
		return fake.SubscribeStub(logger, spec)
	} else {
		return fake.subscribeReturns.result1
	}
}

func (fake *FakeServiceSubscriber) SubscribeCallCount() int {
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	return len(fake.subscribeArgsForCall)
}

func (fake *FakeServiceSubscriber) SubscribeArgsForCall(i int) (lager.Logger, apihub.ServiceSpec) {
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	return fake.subscribeArgsForCall[i].logger, fake.subscribeArgsForCall[i].spec
}

func (fake *FakeServiceSubscriber) SubscribeReturns(result1 error) {
	fake.SubscribeStub = nil
	fake.subscribeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeServiceSubscriber) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.subscribeMutex.RLock()
	defer fake.subscribeMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeServiceSubscriber) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ apihub.ServiceSubscriber = new(FakeServiceSubscriber)
